// src/lib/adapters/react/useStoreValues.ts
import { getObjSnapshot, type ObjSnapshot } from "@/lib/helpers/getObjSnapshot";
import { subscribeToObj } from "@/lib/helpers/subscribeToObj";
import { useEffect, useState } from "react";

/**
 * Given an object that may contain stores, returns a new object with the same
 * keys, but with the stores replaced with their values.
 *
 * @export
 * @template T
 * @returns {*}
 */
export function useStoreValues<T extends {}>(obj: T): ObjSnapshot<T> {
  const [res, setRes] = useState(() => getObjSnapshot(obj));

  useEffect(() => {
    return subscribeToObj(obj, () => {
      setRes(getObjSnapshot(obj));
    });
  }, []);

  return res;
}

// src/lib/adapters/solid/useStoreValues.ts
import { getObjSnapshot, type ObjSnapshot } from "@/lib/helpers/getObjSnapshot";
import { subscribeToObj } from "@/lib/helpers/subscribeToObj";
import { useEffect, useState } from "react";
import { createSignal, onCleanup, type Accessor } from "solid-js";

/**
 * Given an object that may contain stores, returns a new object with the same
 * keys, but with the stores replaced with their values.
 *
 * @export
 * @template T
 * @returns {*}
 */
export function useStoreValues<T extends {}>(obj: T): Accessor<ObjSnapshot<T>> {
  const [res, setRes] = createSignal(getObjSnapshot(obj));

  onCleanup(
    subscribeToObj(obj, () => {
      setRes(() => getObjSnapshot(obj));
    })
  );

  return res;
}
